### PR TITLE
Fix GeoIP_database_info truncation issue.

### LINKED ISSUE #79: Fail: [test-geoip] Copyright keyword not found
The GeoIP_database_info function in libGeoIP/GeoIP.c only returns "GEO-106FREE 20160503 Build 1 Copy" and it causes the test-geoip fails. Would you take a look?

OS: Centos 7.2.1511
kernel: 3.10.0-327.10.1.el7.x86_64
gcc: 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)

Error message:
======================================
   GeoIP 1.6.9: test/test-suite.log
======================================

# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test-geoip
================

Error reading database info (got GEO-106FREE 20160503 Build 1 Copy).
Error reading database info (got GEO-106FREE 20160503 Build 1 Copy).

### PR DESCRIPTION
**Pull request by oschwald**
Closes #79.

### CODE REVIEW

File: libGeoIP/GeoIP.c [hunk 1]
```diff
@@ -2044,23 +2044,24 @@ char *GeoIP_database_info(GeoIP * gi)
...
-    if (hasStructureInfo == 1) {
+    if (has_structure_info) {
         offset -= 6;
         if (offset < 0) {
             return NULL;
         }
     } else {
         /* no structure info, must be pre Sep 2002 database, go back to end */
-        offset -= 3;
+        offset = gi->size - 3;
```
Comment (oschwald) [inline libGeoIP/GeoIP.c]: This is the fix for #79.
